export enum EHomeworksAction {
  USER_HOMEWORKS_FETCH = 'USER_HOMEWORKS_FETCH',
  USER_HOMEWORKS_FETCHED = 'USER_HOMEWORKS_FETCHED',
  USER_HOMEWORKS_REVOKE = 'USER_HOMEWORKS_REVOKE',
  HOMEWORKS_FETCH = 'HOMEWORKS_FETCH',
  HOMEWORKS_FETCHED = 'HOMEWORKS_FETCHED',
  HOMEWORKS_REVOKE = 'HOMEWORKS_REVOKE',
}
