export enum ETestingAction {
  TEST_START_REQUEST = 'TEST_START_REQUEST',
  TEST_FETCH = 'TEST_FETCH',
  TEST_FETCHED = 'TEST_FETCHED',
  TEST_COMPLETE_REQUEST = 'TEST_COMPLETE_REQUEST',
  TEST_STATUS_FETCH = 'TEST_STATUS_FETCH',
  TEST_STATUS_FETCHED = 'TEST_STATUS_FETCHED',
  TEST_STATE_FETCH = 'TEST_STATE_FETCH',
  TEST_STATE_FETCHED = 'TEST_STATE_FETCHED',
  TEST_SAVE_ANSWER_REQUEST = 'TEST_SAVE_ANSWER_REQUEST',
  TEST_SAVE_ANSWER = 'TEST_SAVE_ANSWER',
  TEST_STATE_UPDATE = 'TEST_STATE_UPDATE',
}
