export enum EUsersAction {
  ACCOUNTS_FETCH = 'ACCOUNTS_FETCH',
  ACCOUNTS_FETCHED = 'ACCOUNTS_FETCHED',
  ACCOUNTS_REVOKE = 'ACCOUNTS_REVOKE',
  ACCOUNTS_DELETE_REQUEST = 'ACCOUNTS_DELETE_REQUEST',
  ACCOUNTS_DELETE = 'ACCOUNTS_DELETE',
}
