export enum AccountRole {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  TEACHER = 'TEACHER',
  HELPER = 'HELPER',
  PUPIL = 'PUPIL',
}

export enum Permission {
  SUBJECT_EDIT = 'SUBJECT_EDIT',
  COURSE_EDIT = 'COURSE_EDIT',
  LESSON_EDIT = 'LESSON_EDIT',
  WEBINAR_EDIT = 'WEBINAR_EDIT',
  ACCOUNT_MANAGEMENT = 'ACCOUNT_MANAGEMENT',
  HOMEWORK_CHECK = 'HOMEWORK_CHECK',
  PARTICIPANT_MANAGEMENT = 'PARTICIPANT_MANAGEMENT',
  KNOWLEDGE_BASE_EDIT = 'LESSON_EDIT',
}

export enum LearningStatus {
  LEARNING = 'LEARNING',
  FINISHED = 'FINISHED',
}
