export enum ECoursesAction {
  SHOP_COURSES_FETCH = 'SHOP_COURSES_FETCH',
  SHOP_COURSES_FETCHED = 'SHOP_COURSES_FETCHED',
  USER_COURSES_FETCH = 'USER_COURSES_FETCH',
  USER_COURSES_FETCHED = 'USER_COURSES_FETCHED',
  ADMIN_COURSES_FETCH = 'ADMIN_COURSES_FETCH',
  ADMIN_COURSES_FETCHED = 'ADMIN_COURSES_FETCHED',
  TEACHER_COURSES_FETCH = 'TEACHER_COURSES_FETCH',
  TEACHER_COURSES_FETCHED = 'TEACHER_COURSES_FETCHED',
  COURSES_REVOKE = 'COURSES_REVOKE',
  COURSE_DELETE_REQUEST = 'COURSE_DELETE_REQUEST',
  COURSE_DELETE = 'COURSE_DELETE',
}
