export enum ELessonsAction {
  LESSONS_FETCH = 'LESSONS_FETCH',
  LESSONS_FETCHED = 'LESSONS_FETCHED',
  LESSONS_REVOKE = 'LESSONS_REVOKE',
  LESSON_DELETE_REQUEST = 'LESSON_DELETE_REQUEST',
  LESSON_DELETE = 'LESSON_DELETE',
}
