export enum EUserAction {
  LOG_IN = 'LOG_IN',
  LOG_IN_REQUEST = 'LOG_IN_REQUEST',
  LOG_IN_SUCCESS = 'LOG_IN_SUCCESS',
  LOG_IN_ERROR = 'LOG_IN_ERROR',
  LOG_OUT = 'LOG_OUT',
  USER_INFO_FETCH = 'USER_INFO_FETCH',
  USER_INFO_FETCHED = 'USER_INFO_FETCHED',
  USER_INFO_REVOKE = 'USER_INFO_REVOKE',
}
