export enum ESubjectsAction {
  SUBJECTS_FETCH = 'SUBJECTS_FETCH',
  SUBJECTS_FETCHED = 'SUBJECTS_FETCHED',
  SUBJECTS_REVOKE = 'SUBJECTS_REVOKE',
  SUBJECT_DELETE_REQUEST = 'SUBJECT_DELETE_REQUEST',
  SUBJECT_DELETE = 'SUBJECT_DELETE',
}
