export const ACCOUNT_ROLES = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  TEACHER: 'TEACHER',
  HELPER: 'HELPER',
  PUPIL: 'PUPIL'
};

export const ADMIN_ROLES = [ACCOUNT_ROLES.ADMIN, ACCOUNT_ROLES.MODERATOR];
export const TEACHER_ROLES = [ACCOUNT_ROLES.TEACHER, ACCOUNT_ROLES.HELPER];

export const PERMISSIONS = {
  SUBJECT_EDIT: 'SUBJECT_EDIT',
  COURSE_EDIT: 'COURSE_EDIT',
  LESSON_EDIT: 'LESSON_EDIT',
  WEBINAR_EDIT: 'WEBINAR_EDIT',
  ACCOUNT_MANAGEMENT: 'ACCOUNT_MANAGEMENT',
  HOMEWORK_CHECK: 'HOMEWORK_CHECK',
  PARTICIPANT_MANAGEMENT: 'PARTICIPANT_MANAGEMENT',
};

export const LEARNING_STATUS = {
  learning: 'learning',
  finished: 'finished'
};

export const APP_BASE_URL = process.env.REACT_APP_BASE_URL;
export const DEFAULT_LOGIN_REDIRECT = '/shop/';
