export enum ETestsAction {
  TEST_FETCH = 'KNOWLEDGE_TEST_FETCH',
  TEST_FETCHED = 'KNOWLEDGE_TEST_FETCHED',
  TEST_REVOKE = 'KNOWLEDGE_TEST_REVOKE',
  TEST_DELETE_REQUEST = 'KNOWLEDGE_TEST_DELETE_REQUEST',
  TEST_DELETE = 'KNOWLEDGE_TEST_DELETE',
  TEST_RESULTS_FETCH = 'TEST_RESULTS_FETCH',
  TEST_RESULTS_FETCHED = 'TEST_RESULTS_FETCHED',
}
